// Code generated by "stringer -type=Nationality -linecomment"; DO NOT EDIT.

package nationality

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[American-1]
	_ = x[Argentinean-2]
	_ = x[Australian-3]
	_ = x[Austrian-4]
	_ = x[Azerbaijani-5]
	_ = x[Bahraini-6]
	_ = x[Belgian-7]
	_ = x[Bolivian-8]
	_ = x[Brazilian-9]
	_ = x[British-10]
	_ = x[Bulgarian-11]
	_ = x[Cameroonian-12]
	_ = x[Canadian-13]
	_ = x[Chilean-14]
	_ = x[Chinese-15]
	_ = x[Colombian-16]
	_ = x[CostaRican-17]
	_ = x[Croatian-18]
	_ = x[Cypriot-19]
	_ = x[Czech-20]
	_ = x[Danish-21]
	_ = x[Dutch-22]
	_ = x[Ecuadorian-23]
	_ = x[English-24]
	_ = x[Emirian-25]
	_ = x[Estonian-26]
	_ = x[Finnish-27]
	_ = x[French-28]
	_ = x[German-29]
	_ = x[Ghanaian-30]
	_ = x[Greek-31]
	_ = x[Guatemalan-32]
	_ = x[Honduran-33]
	_ = x[HongKonger-34]
	_ = x[Hungarian-35]
	_ = x[Icelander-36]
	_ = x[Indian-37]
	_ = x[Indonesian-38]
	_ = x[Irish-39]
	_ = x[Israeli-40]
	_ = x[Italian-41]
	_ = x[Jamaican-42]
	_ = x[Japanese-43]
	_ = x[Jordanian-44]
	_ = x[Kuwaiti-45]
	_ = x[Latvian-46]
	_ = x[Lebanese-47]
	_ = x[Lithuanian-48]
	_ = x[Luxembourger-49]
	_ = x[Malaysian-50]
	_ = x[Maltese-51]
	_ = x[Mexican-52]
	_ = x[Monegasque-53]
	_ = x[NewZealander-54]
	_ = x[Nicaraguan-55]
	_ = x[NorthernIrish-56]
	_ = x[Norwegian-57]
	_ = x[Omani-58]
	_ = x[Pakistani-59]
	_ = x[Panamanian-60]
	_ = x[Paraguayan-61]
	_ = x[Peruvian-62]
	_ = x[Polish-63]
	_ = x[Portuguese-64]
	_ = x[Qatari-65]
	_ = x[Romanian-66]
	_ = x[Russian-67]
	_ = x[Salvadoran-68]
	_ = x[Saudi-69]
	_ = x[Scottish-70]
	_ = x[Serbian-71]
	_ = x[Singaporean-72]
	_ = x[Slovakian-73]
	_ = x[Slovenian-74]
	_ = x[SouthKorean-75]
	_ = x[SouthAfrican-76]
	_ = x[Spanish-77]
	_ = x[Swedish-78]
	_ = x[Swiss-79]
	_ = x[Thai-80]
	_ = x[Turkish-81]
	_ = x[Uruguayan-82]
	_ = x[Ukrainian-83]
	_ = x[Venezuelan-84]
	_ = x[Welsh-85]
	_ = x[Barbadian-86]
	_ = x[Vietnamese-87]
}

const _Nationality_name = "AmericanArgentineanAustralianAustrianAzerbaijaniBahrainiBelgianBolivianBrazilianBritishBulgarianCameroonianCanadianChileanChineseColombianCostaRicanCroatianCypriotCzechDanishDutchEcuadorianEnglishEmirianEstonianFinnishFrenchGermanGhanaianGreekGuatemalanHonduranHong KongerHungarianIcelanderIndianIndonesianIrishIsraeliItalianJamaicanJapaneseJordanianKuwaitiLatvianLebaneseLithuanianLuxembourgerMalaysianMalteseMexicanMonegasqueNew ZealanderNicaraguanNorthern IrishNorwegianOmaniPakistaniPanamanianParaguayanPeruvianPolishPortugueseQatariRomanianRussianSalvadoranSaudiScottishSerbianSingaporeanSlovakianSlovenianSouth KoreanSouth AfricanSpanishSwedishSwissThaiTurkishUruguayanUkrainianVenezuelanWelshBarbadianVietnamese"

var _Nationality_index = [...]uint16{0, 8, 19, 29, 37, 48, 56, 63, 71, 80, 87, 96, 107, 115, 122, 129, 138, 148, 156, 163, 168, 174, 179, 189, 196, 203, 211, 218, 224, 230, 238, 243, 253, 261, 272, 281, 290, 296, 306, 311, 318, 325, 333, 341, 350, 357, 364, 372, 382, 394, 403, 410, 417, 427, 440, 450, 464, 473, 478, 487, 497, 507, 515, 521, 531, 537, 545, 552, 562, 567, 575, 582, 593, 602, 611, 623, 636, 643, 650, 655, 659, 666, 675, 684, 694, 699, 708, 718}

func (i Nationality) String() string {
	i -= 1
	if i >= Nationality(len(_Nationality_index)-1) {
		return "Nationality(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Nationality_name[_Nationality_index[i]:_Nationality_index[i+1]]
}
