// Code generated by "stringer -type=Team -linecomment"; DO NOT EDIT.

package team

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mercedes-0]
	_ = x[Ferrari-1]
	_ = x[RedBullRacing-2]
	_ = x[Williams-3]
	_ = x[AstonMartin-4]
	_ = x[Alpine-5]
	_ = x[AlphaTauri-6]
	_ = x[Haas-7]
	_ = x[McLaren-8]
	_ = x[AlfaRomeo-9]
	_ = x[McLaren1988-10]
	_ = x[McLaren1991-11]
	_ = x[Williams1992-12]
	_ = x[Ferrari1995-13]
	_ = x[Williams1996-14]
	_ = x[McLaren1998-15]
	_ = x[Ferrari2002-16]
	_ = x[Ferrari2004-17]
	_ = x[Renault2006-18]
	_ = x[Ferrari2007-19]
	_ = x[McLaren2008-20]
	_ = x[RedBull2010-21]
	_ = x[Ferrari1976-22]
	_ = x[ARTGrandPrix-23]
	_ = x[CamposVexatecRacing-24]
	_ = x[Carlin-25]
	_ = x[CharouzRacingSystem-26]
	_ = x[DAMS-27]
	_ = x[RussianTime-28]
	_ = x[MPMotorsport-29]
	_ = x[Pertamina-30]
	_ = x[McLaren1990-31]
	_ = x[Trident-32]
	_ = x[BWTArden-33]
	_ = x[McLaren1976-34]
	_ = x[Lotus1972-35]
	_ = x[Ferrari1979-36]
	_ = x[McLaren1982-37]
	_ = x[Williams2003-38]
	_ = x[Brawn2009-39]
	_ = x[Lotus1978-40]
	_ = x[F1GenericCar-41]
	_ = x[ArtGP2019-42]
	_ = x[Campos2019-43]
	_ = x[Carlin2019-44]
	_ = x[SauberJuniorCharouz2019-45]
	_ = x[Dams2019-46]
	_ = x[UniVirtuosi2019-47]
	_ = x[MPMotorsport2019-48]
	_ = x[Prema2019-49]
	_ = x[Trident2019-50]
	_ = x[Arden2019-51]
	_ = x[Benetton1994-53]
	_ = x[Benetton1995-54]
	_ = x[Ferrari2000-55]
	_ = x[Jordan1991-56]
	_ = x[Ferrari1990-63]
	_ = x[McLaren2010-64]
	_ = x[Ferrari2010-64]
	_ = x[ArtGP2020-70]
	_ = x[Campos2020-71]
	_ = x[Carlin2020-72]
	_ = x[Charouz2020-73]
	_ = x[Dam2020-74]
	_ = x[UniVirtuosi2020-75]
	_ = x[MPMotorsport2020-76]
	_ = x[Prema2020-77]
	_ = x[Trident2020-78]
	_ = x[BWT2020-79]
	_ = x[Hitech2020-80]
	_ = x[Mercedes2020-85]
	_ = x[Ferrari2020-86]
	_ = x[RedBull2020-87]
	_ = x[Williams2020-88]
	_ = x[RacingPoint2020-89]
	_ = x[Renault2020-90]
	_ = x[AlphaTauri2020-91]
	_ = x[Haas2020-92]
	_ = x[McLaren2020-93]
	_ = x[AlfaRomeo2020-94]
	_ = x[AstonMartinDB11V12-95]
	_ = x[AstonMartinVantageF1Edition-96]
	_ = x[AstonMartinVantageSafetyCar-97]
	_ = x[FerrariF8Tributo-98]
	_ = x[FerrariRoma-99]
	_ = x[McLaren720S-100]
	_ = x[McLarenArtura-101]
	_ = x[MercedesAMGGTBlackSeriesSafetyCar-102]
	_ = x[MercedesAMGGTRPro-103]
	_ = x[F1CustomTeam-104]
	_ = x[Prema2021-106]
	_ = x[UniVirtuosi2021-107]
	_ = x[Carlin2021-108]
	_ = x[Hitech2021-109]
	_ = x[ArtGP2021-110]
	_ = x[MPMotorsport2021-111]
	_ = x[Charouz2021-112]
	_ = x[Dams2021-113]
	_ = x[Campos2021-114]
	_ = x[BWT2021-115]
	_ = x[Trident2021-116]
	_ = x[MercedesAMGGTBlackSeries-117]
	_ = x[MyTeam-255]
}

const (
	_Team_name_0 = "MercedesFerrariRedBull RacingWilliamsAston MartinAlpineAlphaTauriHaasMcLarenAlfa RomeoMcLaren 1988McLaren 1991Williams 1992Ferrari 1995Williams 1996McLaren 1998Ferrari 2002Ferrari 2004Renault 2006Ferrari 2007McLaren 2008RedBull 2010Ferrari 1976ART Grand PrixCampos Vexatec RacingCarlinCharouz Racing SystemDAMSRussian TimeMP MotorsportPertaminaMcLaren 1990TridentBWT ArdenMcLaren 1976Lotus 1972Ferrari 1979McLaren 1982Williams 2003Brawn 2009Lotus 1978F1 Generic CarArtGP 2019Campos 2019Carlin 2019Sauber Junior Charouz 2019Dams 2019Uni Virtuosi 2019MP Motorsport 2019Prema 2019Trident 2019Arden 2019"
	_Team_name_1 = "Benetton 1994Benetton 1995Ferrari 2000Jordan 1991"
	_Team_name_2 = "Ferrari 1990McLaren 2010"
	_Team_name_3 = "ArtGP 2020Campos 2020Carlin 2020Charouz 2020Dam 2020Uni Virtuosi 2020MP Motorsport 2020Prema 2020Trident 2020BWT 2020Hitech 2020"
	_Team_name_4 = "Mercedes 2020Ferrari 2020RedBull 2020Williams 2020Racing Point 2020Renault 2020AlphaTauri 2020Haas 2020McLaren 2020Alfa Romeo 2020Aston Martin DB11 V12Aston Martin Vantage F1 EditionAston Martin Vantage Safety CarFerrari F8 TributoFerrari RomaMcLaren 720SMcLaren ArturaMercedes AMG GT Black Series Safety CarMercedes AMG GTR ProF1 Custom Team"
	_Team_name_5 = "Prema 2021Uni Virtuosi 2021Carlin 2021Hitech 2021ArtGP 2021MP Motorsport 2021Charouz 2021Dams 2021Campos 2021BWT 2021Trident 2021Mercedes AMG GT Black Series"
	_Team_name_6 = "My Team"
)

var (
	_Team_index_0 = [...]uint16{0, 8, 15, 29, 37, 49, 55, 65, 69, 76, 86, 98, 110, 123, 135, 148, 160, 172, 184, 196, 208, 220, 232, 244, 258, 279, 285, 306, 310, 322, 335, 344, 356, 363, 372, 384, 394, 406, 418, 431, 441, 451, 465, 475, 486, 497, 523, 532, 549, 567, 577, 589, 599}
	_Team_index_1 = [...]uint8{0, 13, 26, 38, 49}
	_Team_index_2 = [...]uint8{0, 12, 24}
	_Team_index_3 = [...]uint8{0, 10, 21, 32, 44, 52, 69, 87, 97, 109, 117, 128}
	_Team_index_4 = [...]uint16{0, 13, 25, 37, 50, 67, 79, 94, 103, 115, 130, 151, 182, 213, 231, 243, 255, 269, 308, 328, 342}
	_Team_index_5 = [...]uint8{0, 10, 27, 38, 49, 59, 77, 89, 98, 109, 117, 129, 157}
)

func (i Team) String() string {
	switch {
	case i <= 51:
		return _Team_name_0[_Team_index_0[i]:_Team_index_0[i+1]]
	case 53 <= i && i <= 56:
		i -= 53
		return _Team_name_1[_Team_index_1[i]:_Team_index_1[i+1]]
	case 63 <= i && i <= 64:
		i -= 63
		return _Team_name_2[_Team_index_2[i]:_Team_index_2[i+1]]
	case 70 <= i && i <= 80:
		i -= 70
		return _Team_name_3[_Team_index_3[i]:_Team_index_3[i+1]]
	case 85 <= i && i <= 104:
		i -= 85
		return _Team_name_4[_Team_index_4[i]:_Team_index_4[i+1]]
	case 106 <= i && i <= 117:
		i -= 106
		return _Team_name_5[_Team_index_5[i]:_Team_index_5[i+1]]
	case i == 255:
		return _Team_name_6
	default:
		return "Team(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
