version: '2.1'
networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: { }
  grafana_data: { }

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.5.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - monitoring

  sample-app:
    build:
      context: ../
    ports:
      - 8080:8080
      - 20777:20777/udp
    expose:
      - 8080
      - 20777/udp
    networks:
      - monitoring
