package driver

// Driver IDs

//go:generate stringer -type=Driver -linecomment
type Driver uint8

const (
	CarlosSainz         Driver = 0   // Carlos Sainz
	DaniilKvyat         Driver = 1   // Daniil Kvyat
	DanielRicciardo     Driver = 2   // Daniel Ricciardo
	FernandoAlonso      Driver = 3   // Fernando Alonso
	FelipeMassa         Driver = 4   // Felipe Massa
	KimiRaikkonen       Driver = 6   // Kimi Raikkonen
	LewisHamilton       Driver = 7   // Lewis Hamilton
	MaxVerstappen       Driver = 9   // Max Verstappen
	NicoHulkenburg      Driver = 10  // Nico Hulkenburg
	KevinMagnussen      Driver = 11  // Kevin Magnussen
	RomainGrosjean      Driver = 12  // Romain Grosjean
	SebastianVettel     Driver = 13  // Sebastian Vettel
	SergioPerez         Driver = 14  // Sergio Perez
	ValtteriBottas      Driver = 15  // Valtteri Bottas
	EstebanOcon         Driver = 17  // Esteban Ocon
	LanceStroll         Driver = 19  // Lance Stroll
	ArronBarnes         Driver = 20  // Arron Barnes
	MartinGiles         Driver = 21  // Martin Giles
	AlexMurray          Driver = 22  // Alex Murray
	LucasRoth           Driver = 23  // Lucas Roth
	IgorCorreia         Driver = 24  // Igor Correia
	SophieLevasseur     Driver = 25  // Sophie Levasseur
	JonasSchiffer       Driver = 26  // Jonas Schiffer
	AlainForest         Driver = 27  // Alain Forest
	JayLetourneau       Driver = 28  // Jay Letourneau
	EstoSaari           Driver = 29  // Esto Saari
	YasarAtiyeh         Driver = 30  // Yasar Atiyeh
	CallistoCalabresi   Driver = 31  // Callisto Calabresi
	NaotaIzum           Driver = 32  // Naota Izum
	HowardClarke        Driver = 33  // Howard Clarke
	WilheimKaufmann     Driver = 34  // Wilheim Kaufmann
	MarieLaursen        Driver = 35  // Marie Laursen
	FlavioNieves        Driver = 36  // Flavio Nieves
	PeterBelousov       Driver = 37  // Peter Belousov
	KlimekMichalski     Driver = 38  // Klimek Michalski
	SantiagoMoreno      Driver = 39  // Santiago Moreno
	BenjaminCoppens     Driver = 40  // Benjamin Coppens
	NoahVisser          Driver = 41  // Noah Visser
	GertWaldmuller      Driver = 42  // Gert Waldmuller
	JulianQuesada       Driver = 43  // Julian Quesada
	DanielJones         Driver = 44  // Daniel Jones
	ArtemMarkelov       Driver = 45  // Artem Markelov
	TadasukeMakino      Driver = 46  // Tadasuke Makino
	SeanGelael          Driver = 47  // Sean Gelael
	NyckDeVries         Driver = 48  // Nyck De Vries
	JackAitken          Driver = 49  // Jack Aitken
	GeorgeRussell       Driver = 50  // George Russell
	MaximilianGunther   Driver = 51  // Maximilian Gunther
	NireiFukuzumi       Driver = 52  // Nirei Fukuzumi
	LucaGhiotto         Driver = 53  // Luca Ghiotto
	LandoNorris         Driver = 54  // Lando Norris
	SergioSetteCamara   Driver = 55  // Sergio Sette Camara
	LouisDeletraz       Driver = 56  // Louis Deletraz
	AntonioFuoco        Driver = 57  // Antonio Fuoco
	CharlesLeclerc      Driver = 58  // Charles Leclerc
	PierreGasly         Driver = 59  // Pierre Gasly
	AlexanderAlbon      Driver = 62  // Alexander Albon
	NicholasLatifi      Driver = 63  // Nicholas Latifi
	DorianBoccolacci    Driver = 64  // Dorian Boccolacci
	NikoKari            Driver = 65  // Niko Kari
	RobertoMerhi        Driver = 66  // Roberto Merhi
	ArjunMaini          Driver = 67  // Arjun Maini
	AlessioLorandi      Driver = 68  // Alessio Lorandi
	RubenMeijer         Driver = 69  // Ruben Meijer
	RashidNair          Driver = 70  // Rashid Nair
	JackTremblay        Driver = 71  // Jack Tremblay
	AntonioGiovinazzi   Driver = 74  // Antonio Giovinazzi
	RobertKubica        Driver = 75  // Robert Kubica
	NobuharuMatsushita  Driver = 78  // Nobuharu Matsushit
	NikitaMazepin       Driver = 79  // Nikita Mazepin
	GuanyaZhou          Driver = 80  // Guanya Zhou
	MickSchumacher      Driver = 81  // Mick Schumacher
	CallumIlott         Driver = 82  // Callum Ilott
	JuanManuelCorrea    Driver = 83  // Juan Manuel Correa
	JordanKing          Driver = 84  // Jordan King
	MahaveerRaghunathan Driver = 85  // Mahaveer Raghunath
	TatianaCalderon     Driver = 86  // Tatiana Calderon
	AnthoineHubert      Driver = 87  // Anthoine Hubert
	GuilianoAlesi       Driver = 88  // Guiliano Alesi
	RalphBoschung       Driver = 89  // Ralph Boschung
	MichaelSchumacher   Driver = 90  // Michael Schumacher
	DanTicktum          Driver = 91  // Dan Ticktum
	MarcusArmstrong     Driver = 92  // Marcus Armstrong
	ChristianLundgaard  Driver = 93  // Christian Lundgaar
	YukiTsunoda         Driver = 94  // Yuki Tsunoda
	JehanDaruvala       Driver = 95  // Jehan Daruvala
	GulhermeSamaia      Driver = 96  // Gulherme Samaia
	PedroPiquet         Driver = 97  // Pedro Piquet
	FelipeDrugovich     Driver = 98  // Felipe Drugovich
	RoberSchwartzman    Driver = 99  // Rober Schwartzman
	RoyNissany          Driver = 100 // Roy Nissany
	MarinoSatorus       Driver = 101 // Marino Satorus
	AidanJackson        Driver = 102 // Aidan Jackson
	CasperAkkerman      Driver = 103 // Casper Akkerman
	JensonButton        Driver = 109 // Jenson Button
	DavidCoulthard      Driver = 110 // David Coulthard
	NicoRosberg         Driver = 111 // Nico Rosberg
	OscarPiastri        Driver = 112 // Oscar Piastri
	LiamLawson          Driver = 113 // Liam Lawson
	JuriVips            Driver = 114 // Juri Vips
	TheoPourchaire      Driver = 115 // Theo Pourchaire
	RichardVerschoor    Driver = 116 // Richard Verschoor
	LirimZendeli        Driver = 117 // Lirim Zendeli
	DavidBeckmann       Driver = 118 // David Beckmann
	GianlucaPetecof     Driver = 119 // Gianluca Petecof
	MatteoNannini       Driver = 120 // Matteo Nannini
	AlessioDeledda      Driver = 121 // Alessio Deledda
	BentViscaal         Driver = 122 // Bent Viscaal
	EnzoFitipaldi       Driver = 123 // Enzo Fitipaldi
	MarkWebber          Driver = 125 // Mark Webber
	JacquesVilleneuve   Driver = 126 // Jacques Villeneuve
)
