// Code generated by "stringer -type=Driver -linecomment"; DO NOT EDIT.

package driver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CarlosSainz-0]
	_ = x[DaniilKvyat-1]
	_ = x[DanielRicciardo-2]
	_ = x[FernandoAlonso-3]
	_ = x[FelipeMassa-4]
	_ = x[KimiRaikkonen-6]
	_ = x[LewisHamilton-7]
	_ = x[MaxVerstappen-9]
	_ = x[NicoHulkenburg-10]
	_ = x[KevinMagnussen-11]
	_ = x[RomainGrosjean-12]
	_ = x[SebastianVettel-13]
	_ = x[SergioPerez-14]
	_ = x[ValtteriBottas-15]
	_ = x[EstebanOcon-17]
	_ = x[LanceStroll-19]
	_ = x[ArronBarnes-20]
	_ = x[MartinGiles-21]
	_ = x[AlexMurray-22]
	_ = x[LucasRoth-23]
	_ = x[IgorCorreia-24]
	_ = x[SophieLevasseur-25]
	_ = x[JonasSchiffer-26]
	_ = x[AlainForest-27]
	_ = x[JayLetourneau-28]
	_ = x[EstoSaari-29]
	_ = x[YasarAtiyeh-30]
	_ = x[CallistoCalabresi-31]
	_ = x[NaotaIzum-32]
	_ = x[HowardClarke-33]
	_ = x[WilheimKaufmann-34]
	_ = x[MarieLaursen-35]
	_ = x[FlavioNieves-36]
	_ = x[PeterBelousov-37]
	_ = x[KlimekMichalski-38]
	_ = x[SantiagoMoreno-39]
	_ = x[BenjaminCoppens-40]
	_ = x[NoahVisser-41]
	_ = x[GertWaldmuller-42]
	_ = x[JulianQuesada-43]
	_ = x[DanielJones-44]
	_ = x[ArtemMarkelov-45]
	_ = x[TadasukeMakino-46]
	_ = x[SeanGelael-47]
	_ = x[NyckDeVries-48]
	_ = x[JackAitken-49]
	_ = x[GeorgeRussell-50]
	_ = x[MaximilianGunther-51]
	_ = x[NireiFukuzumi-52]
	_ = x[LucaGhiotto-53]
	_ = x[LandoNorris-54]
	_ = x[SergioSetteCamara-55]
	_ = x[LouisDeletraz-56]
	_ = x[AntonioFuoco-57]
	_ = x[CharlesLeclerc-58]
	_ = x[PierreGasly-59]
	_ = x[AlexanderAlbon-62]
	_ = x[NicholasLatifi-63]
	_ = x[DorianBoccolacci-64]
	_ = x[NikoKari-65]
	_ = x[RobertoMerhi-66]
	_ = x[ArjunMaini-67]
	_ = x[AlessioLorandi-68]
	_ = x[RubenMeijer-69]
	_ = x[RashidNair-70]
	_ = x[JackTremblay-71]
	_ = x[AntonioGiovinazzi-74]
	_ = x[RobertKubica-75]
	_ = x[NobuharuMatsushita-78]
	_ = x[NikitaMazepin-79]
	_ = x[GuanyaZhou-80]
	_ = x[MickSchumacher-81]
	_ = x[CallumIlott-82]
	_ = x[JuanManuelCorrea-83]
	_ = x[JordanKing-84]
	_ = x[MahaveerRaghunathan-85]
	_ = x[TatianaCalderon-86]
	_ = x[AnthoineHubert-87]
	_ = x[GuilianoAlesi-88]
	_ = x[RalphBoschung-89]
	_ = x[MichaelSchumacher-90]
	_ = x[DanTicktum-91]
	_ = x[MarcusArmstrong-92]
	_ = x[ChristianLundgaard-93]
	_ = x[YukiTsunoda-94]
	_ = x[JehanDaruvala-95]
	_ = x[GulhermeSamaia-96]
	_ = x[PedroPiquet-97]
	_ = x[FelipeDrugovich-98]
	_ = x[RoberSchwartzman-99]
	_ = x[RoyNissany-100]
	_ = x[MarinoSatorus-101]
	_ = x[AidanJackson-102]
	_ = x[CasperAkkerman-103]
	_ = x[JensonButton-109]
	_ = x[DavidCoulthard-110]
	_ = x[NicoRosberg-111]
	_ = x[OscarPiastri-112]
	_ = x[LiamLawson-113]
	_ = x[JuriVips-114]
	_ = x[TheoPourchaire-115]
	_ = x[RichardVerschoor-116]
	_ = x[LirimZendeli-117]
	_ = x[DavidBeckmann-118]
	_ = x[GianlucaPetecof-119]
	_ = x[MatteoNannini-120]
	_ = x[AlessioDeledda-121]
	_ = x[BentViscaal-122]
	_ = x[EnzoFitipaldi-123]
	_ = x[MarkWebber-125]
	_ = x[JacquesVilleneuve-126]
}

const (
	_Driver_name_0 = "Carlos SainzDaniil KvyatDaniel RicciardoFernando AlonsoFelipe Massa"
	_Driver_name_1 = "Kimi RaikkonenLewis Hamilton"
	_Driver_name_2 = "Max VerstappenNico HulkenburgKevin MagnussenRomain GrosjeanSebastian VettelSergio PerezValtteri Bottas"
	_Driver_name_3 = "Esteban Ocon"
	_Driver_name_4 = "Lance StrollArron BarnesMartin GilesAlex MurrayLucas RothIgor CorreiaSophie LevasseurJonas SchifferAlain ForestJay LetourneauEsto SaariYasar AtiyehCallisto CalabresiNaota IzumHoward ClarkeWilheim KaufmannMarie LaursenFlavio NievesPeter BelousovKlimek MichalskiSantiago MorenoBenjamin CoppensNoah VisserGert WaldmullerJulian QuesadaDaniel JonesArtem MarkelovTadasuke MakinoSean GelaelNyck De VriesJack AitkenGeorge RussellMaximilian GuntherNirei FukuzumiLuca GhiottoLando NorrisSergio Sette CamaraLouis DeletrazAntonio FuocoCharles LeclercPierre Gasly"
	_Driver_name_5 = "Alexander AlbonNicholas LatifiDorian BoccolacciNiko KariRoberto MerhiArjun MainiAlessio LorandiRuben MeijerRashid NairJack Tremblay"
	_Driver_name_6 = "Antonio GiovinazziRobert Kubica"
	_Driver_name_7 = "Nobuharu MatsushitNikita MazepinGuanya ZhouMick SchumacherCallum IlottJuan Manuel CorreaJordan KingMahaveer RaghunathTatiana CalderonAnthoine HubertGuiliano AlesiRalph BoschungMichael SchumacherDan TicktumMarcus ArmstrongChristian LundgaarYuki TsunodaJehan DaruvalaGulherme SamaiaPedro PiquetFelipe DrugovichRober SchwartzmanRoy NissanyMarino SatorusAidan JacksonCasper Akkerman"
	_Driver_name_8 = "Jenson ButtonDavid CoulthardNico RosbergOscar PiastriLiam LawsonJuri VipsTheo PourchaireRichard VerschoorLirim ZendeliDavid BeckmannGianluca PetecofMatteo NanniniAlessio DeleddaBent ViscaalEnzo Fitipaldi"
	_Driver_name_9 = "Mark WebberJacques Villeneuve"
)

var (
	_Driver_index_0 = [...]uint8{0, 12, 24, 40, 55, 67}
	_Driver_index_1 = [...]uint8{0, 14, 28}
	_Driver_index_2 = [...]uint8{0, 14, 29, 44, 59, 75, 87, 102}
	_Driver_index_4 = [...]uint16{0, 12, 24, 36, 47, 57, 69, 85, 99, 111, 125, 135, 147, 165, 175, 188, 204, 217, 230, 244, 260, 275, 291, 302, 317, 331, 343, 357, 372, 383, 396, 407, 421, 439, 453, 465, 477, 496, 510, 523, 538, 550}
	_Driver_index_5 = [...]uint8{0, 15, 30, 47, 56, 69, 80, 95, 107, 118, 131}
	_Driver_index_6 = [...]uint8{0, 18, 31}
	_Driver_index_7 = [...]uint16{0, 18, 32, 43, 58, 70, 88, 99, 117, 133, 148, 162, 176, 194, 205, 221, 239, 251, 265, 280, 292, 308, 325, 336, 350, 363, 378}
	_Driver_index_8 = [...]uint8{0, 13, 28, 40, 53, 64, 73, 88, 105, 118, 132, 148, 162, 177, 189, 203}
	_Driver_index_9 = [...]uint8{0, 11, 29}
)

func (i Driver) String() string {
	switch {
	case i <= 4:
		return _Driver_name_0[_Driver_index_0[i]:_Driver_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _Driver_name_1[_Driver_index_1[i]:_Driver_index_1[i+1]]
	case 9 <= i && i <= 15:
		i -= 9
		return _Driver_name_2[_Driver_index_2[i]:_Driver_index_2[i+1]]
	case i == 17:
		return _Driver_name_3
	case 19 <= i && i <= 59:
		i -= 19
		return _Driver_name_4[_Driver_index_4[i]:_Driver_index_4[i+1]]
	case 62 <= i && i <= 71:
		i -= 62
		return _Driver_name_5[_Driver_index_5[i]:_Driver_index_5[i+1]]
	case 74 <= i && i <= 75:
		i -= 74
		return _Driver_name_6[_Driver_index_6[i]:_Driver_index_6[i+1]]
	case 78 <= i && i <= 103:
		i -= 78
		return _Driver_name_7[_Driver_index_7[i]:_Driver_index_7[i+1]]
	case 109 <= i && i <= 123:
		i -= 109
		return _Driver_name_8[_Driver_index_8[i]:_Driver_index_8[i+1]]
	case 125 <= i && i <= 126:
		i -= 125
		return _Driver_name_9[_Driver_index_9[i]:_Driver_index_9[i+1]]
	default:
		return "Driver(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
