// Code generated by "stringer -type=Mode -linecomment"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventMode-0]
	_ = x[GrandPrix-3]
	_ = x[TimeTrial-5]
	_ = x[Splitscreen-6]
	_ = x[OnlineCustom-7]
	_ = x[OnlineLeague-8]
	_ = x[CareerInvitational-11]
	_ = x[ChampionshipInvitational-12]
	_ = x[Championship-13]
	_ = x[OnlineChampionship-14]
	_ = x[OnlineWeeklyEvent-15]
	_ = x[Career22-19]
	_ = x[Career22Online-20]
	_ = x[Benchmark-127]
}

const (
	_Mode_name_0 = "Event Mode"
	_Mode_name_1 = "Grand Prix"
	_Mode_name_2 = "Time TrialSplitscreenOnline CustomOnline League"
	_Mode_name_3 = "Career InvitationalChampionship InvitationalChampionshipOnline ChampionshipOnline Weekly Event"
	_Mode_name_4 = "Career ‘22Career ’22 Online"
	_Mode_name_5 = "Benchmark"
)

var (
	_Mode_index_2 = [...]uint8{0, 10, 21, 34, 47}
	_Mode_index_3 = [...]uint8{0, 19, 44, 56, 75, 94}
	_Mode_index_4 = [...]uint8{0, 12, 31}
)

func (i Mode) String() string {
	switch {
	case i == 0:
		return _Mode_name_0
	case i == 3:
		return _Mode_name_1
	case 5 <= i && i <= 8:
		i -= 5
		return _Mode_name_2[_Mode_index_2[i]:_Mode_index_2[i+1]]
	case 11 <= i && i <= 15:
		i -= 11
		return _Mode_name_3[_Mode_index_3[i]:_Mode_index_3[i+1]]
	case 19 <= i && i <= 20:
		i -= 19
		return _Mode_name_4[_Mode_index_4[i]:_Mode_index_4[i+1]]
	case i == 127:
		return _Mode_name_5
	default:
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
