// Code generated by "stringer -type=Penalty -linecomment"; DO NOT EDIT.

package penalty

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriveThrough-0]
	_ = x[StopGo-1]
	_ = x[Grid-2]
	_ = x[Reminder-3]
	_ = x[Time-4]
	_ = x[Warning-5]
	_ = x[Disqualified-6]
	_ = x[RemoveFromFormationLap-7]
	_ = x[ParkedTooLongTimer-8]
	_ = x[TypeRegulations-9]
	_ = x[ThisLapInvalidated-10]
	_ = x[ThisAndNextNextLapInvalidated-11]
	_ = x[ThisLapInvalidatedWithoutReason-12]
	_ = x[ThisAndNextLapInvalidatedWithoutReason-13]
	_ = x[ThisAndPrevLapInvalidated-14]
	_ = x[ThisAndPrevLapInvalidatedWithoutReason-15]
	_ = x[Retired-16]
	_ = x[BlackFlagTimer-17]
}

const _Penalty_name = "Drive throughStop GoGrid penaltyPenalty reminderTime penaltyWarningDisqualifiedRemoved from formation lapParked too long timerTyre regulationsThis lap invalidatedThis and next lap invalidatedThis lap invalidated without reasonThis and next lap invalidated without reasonThis and previous lap invalidatedThis and previous lap invalidated without reasonRetiredBlack flag timer"

var _Penalty_index = [...]uint16{0, 13, 20, 32, 48, 60, 67, 79, 105, 126, 142, 162, 191, 226, 270, 303, 351, 358, 374}

func (i Penalty) String() string {
	if i >= Penalty(len(_Penalty_index)-1) {
		return "Penalty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Penalty_name[_Penalty_index[i]:_Penalty_index[i+1]]
}
