// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package session

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[P1-1]
	_ = x[P2-2]
	_ = x[P3-3]
	_ = x[ShortP-4]
	_ = x[Q1-5]
	_ = x[Q2-6]
	_ = x[Q3-7]
	_ = x[ShortQ-8]
	_ = x[OSQ-9]
	_ = x[R-10]
	_ = x[R2-11]
	_ = x[R3-12]
	_ = x[TimeTrial-13]
}

const _Type_name = "UnknownP1P2P3Short PQ1Q2Q3Short QOSQRR2R3Time Trial"

var _Type_index = [...]uint8{0, 7, 9, 11, 13, 20, 22, 24, 26, 33, 36, 37, 39, 41, 51}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
